name: update zapret list

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# Даем права на запись в репозиторий
permissions:
  contents: write

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: download fresh domains list
        run: |
          curl -sSL "https://p.thenewone.lol/domains-export.txt" -o domains-export.txt

      - name: commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 1. Сначала стягиваем возможные изменения из репозитория, пока индекс чист
          git pull --rebase origin main || true
          
          # 2. Добавляем скачанный файл в индекс
          git add domains-export.txt
          
          # 3. Проверяем, изменился ли файл. Если да — коммитим и пушим
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update domains list"
            git push
          else
            echo "No changes in domains list. Skipping commit."
          fi
